name: Provision GKE Clsuter with Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GKE
        run: |
          echo "Deploying to GKE..."
